### ISSUE TITLE
Calibration data not saved fully

### ISSUE THREAD

**Issue by piotrrusiecki** [Freenove/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi#19]
Hi, I think you're not saving calibration for two legs:

    def save(self):
        command=cmd.CMD_CALIBRATION+'#'+'save'+'\n'
        self.client.send_data(command)

        self.point[0][0] = self.one_x.text()
        self.point[0][1] = self.one_y.text()
        self.point[0][2] = self.one_z.text()

        self.point[1][0] = self.two_x.text()
        self.point[1][1] = self.two_y.text()
        self.point[1][2] = self.two_z.text()

        self.point[2][0] = self.three_x.text()
        self.point[2][1] = self.three_y.text()
        self.point[2][2] = self.three_z.text()

        self.point[3][0] = self.four_x.text()
        self.point[3][1] = self.four_y.text()
        self.point[3][2] = self.four_z.text()

It misses:

        self.point[4][0] = self.five_x.text()
        self.point[4][1] = self.five_y.text()
        self.point[4][2] = self.five_z.text()

        self.point[5][0] = self.six_x.text()
        self.point[5][1] = self.six_y.text()
        self.point[5][2] = self.six_z.text()

**Comment by DenzelChen** [comment]
Thank you. We have updated the code.
